### ISSUE TITLE
[Bug] `LspLensOn` has no effect

### ISSUE THREAD

**Issue by pidgeon777** [VidocqH/lsp-lens.nvim#27]
I'm testing the plugin with a `C` source code with `clangd` enabled.

Nohing changes when `LspLensOn` is executed.

My `Lazy` config:

```lua
{
  'VidocqH/lsp-lens.nvim',
  config = function()
    require'lsp-lens'.setup({
      enable = true,
      include_declaration = false,      -- Reference include declaration
      sections = {                      -- Enable / Disable specific request
        definition = false,
        references = true,
        implements = true,
      },
      ignore_filetype = {
        -- "prisma",
      },
    })
  end,
  enabled = lvim.builtin.lsp_lens.active,
}
```

`clangd` LSP is working as expected, though.

Also I tried with other filetypes, nothing happens.

Neovim version: `v0.9.2`

**Comment by jellydn** [comment]
I've got similar issue with Lsp Len and make it works by pin to the commit

```lua
 -- disable lsp-inlayhints and lsp lenf if that is nightly version, will remove when 0.10.0 is stable
local is_stable_version = true
if vim.fn.has("nvim-0.10.0") == 1 then
  is_stable_version = false
end

  return {
    -- Displaying references and definition infos upon functions
    "VidocqH/lsp-lens.nvim",
    -- Pin to commit due to bug with recent change
    commit = "13d25ad8bd55aa34cc0aa3082e78a4157c401346",
    event = "BufRead",
    -- Disable lsp lens if that is nightly version
    enabled = is_stable_version,
    opts = {
      enable = true,
    },
    keys = {
      {
        -- LspLensToggle
        "<leader>uL",
        "<cmd>LspLensToggle<CR>",
        desc = "LSP Len Toggle",
      },
    },
  },
```

**Comment by pidgeon777** [comment]
I confirm that with that commit it works, hopefully this will be fixed in the latest `master` commit.

**Comment by mcauley-penney** [comment]
@pidgeon777 I'm not experiencing this issue but decided to look into it. Firstly, I installed `v0.9.2` and put in the configuration in the original issue comment. I receive this error:

![image](https://github.com/VidocqH/lsp-lens.nvim/assets/59481467/33fcba36-2da1-425a-876b-20ca82cf8780)

Looking at `lsp-lens.nvim/lua/lsp-lens/config.lua`, sections are functions, not booleans, hence the error. If I understand correctly, the configuration in the readme is incorrect, and the config in the original issue comment obviously has the same problem. Removing the `section` option fixes it for me. Idk if this really solves your problem, but please sound off and let me know if modifying that config section does anything for you.

**Comment by VidocqH** [comment]
> @pidgeon777 I'm not experiencing this issue but decided to look into it. Firstly, I installed `v0.9.2` and put in the configuration in the original issue comment. I receive this error:
> 
> ![image](https://user-images.githubusercontent.com/59481467/277132268-33fcba36-2da1-425a-876b-20ca82cf8780.png)
> 
> Looking at `lsp-lens.nvim/lua/lsp-lens/config.lua`, sections are functions, not booleans, hence the error. If I understand correctly, the configuration in the readme is incorrect and the config in the original issue comment has the same problem. Removing the `section` option or changing the values to functions fixes it for me. Idk if this really solves your problem but please sound off and let me know if modifying that config section does anything for you. If not, more information may be useful.
> 
> Edit: ~Right after I wrote this, I removed your config and went back to mine. I tried it with 0.9.2 and am getting the same issue, where lsp-lens doesn't activate, and all the `LspLens...` functions are unavailable. Looking into it.~ I had an error in my config.

Sorry for the late reply. It should be fixed now.

**Comment by jellydn** [comment]
> It should be fixed now.

Thanks. It works for me.

**Comment by daUnknownCoder** [comment]
bro still doesnt work for me, i installed it and tried it first in the `lua` language, mostly my nvim's config
![2023-10-24-233743_hyprshot](https://github.com/VidocqH/lsp-lens.nvim/assets/84800625/264b6265-62b2-4973-9417-6303d7cf34a2)

lsp_lens is on `LspLensOn`

**Comment by VidocqH** [comment]
> bro still doesnt work for me, i installed it and tried it first in the `lua` language, mostly my nvim's config ![2023-10-24-233743_hyprshot](https://user-images.githubusercontent.com/84800625/277762875-264b6265-62b2-4973-9417-6303d7cf34a2.png)
> 
> lsp_lens is on `LspLensOn`
> 
> i also tried pinning to commit `13d25ad8bd55aa34cc0aa3082e78a4157c401346`

Can you try define a non-anonymous function?
```lua
function hello()
  print("Hello, World")
end
```

**Comment by daUnknownCoder** [comment]
> ```lua
> function hello()
>   print("Hello, World")
> end
> ```

![2023-10-25-233238_hyprshot](https://github.com/VidocqH/lsp-lens.nvim/assets/84800625/1bbf0b82-ae0c-41f9-ae84-ec6775a79c5f)

still doesnt work, `LspLensOn` is enabled

i forgot this earlier, this is my config:
```lua
return {
  "VidocqH/lsp-lens.nvim",
  lazy = true,
  event = "LspAttach",
  opts = {
    enable = true,
    commit = "13d25ad8bd55aa34cc0aa3082e78a4157c401346",
    include_declaration = true,
    sections = {
      definitions = true,
    },
  },
}
```

**Comment by mcauley-penney** [comment]
> > ```lua
> > function hello()
> >   print("Hello, World")
> > end
> > ```
> 
> ![2023-10-25-233238_hyprshot](https://user-images.githubusercontent.com/84800625/278105791-1bbf0b82-ae0c-41f9-ae84-ec6775a79c5f.png)
> 
> still doesnt work, `LspLensOn` is enabled
> 
> i forgot this earlier, this is my config:
> 
> ```lua
> return {
>   "VidocqH/lsp-lens.nvim",
>   lazy = true,
>   event = "LspAttach",
>   opts = {
>     enable = true,
>     commit = "13d25ad8bd55aa34cc0aa3082e78a4157c401346",
>     include_declaration = true,
>     sections = {
>       definitions = true,
>     },
>   },
> }
> ```
> 
> also tried moving `opts` inside `require("lsp-lens").setup({...})`
> 
> ![2023-10-25-233611_hyprshot](https://user-images.githubusercontent.com/84800625/278106689-de673f0d-d1c8-42c8-b38d-2c6a5e1b3c6e.png)

Firstly, "definitions" should be singular. I'll test this when I'm available and debug it.

**Comment by daUnknownCoder** [comment]
thanks but i got it to work, even without pinning it to a commit:

![2023-10-26-215723_hyprshot](https://github.com/VidocqH/lsp-lens.nvim/assets/84800625/37a5cb87-cce0-46ba-8933-04cca29368fc)

**Comment by pidgeon777** [comment]
I confirm the latest commit fixed the issue. This can be closed if needed.
